### ISSUE TITLE
使用语义分割预训练好的模型，效果很差

### ISSUE THREAD

**Issue by yezi1996** [yanx27/Pointnet_Pointnet2_pytorch#115] opened 2021-06-18 12:14 UTC
你好，使用默认的预先训练好的S3DIS语义分割模型，效果很差，如下：

PARAMETER ...
Namespace(batch_size=32, gpu='0', log_dir='pointnet2_sem_seg', num_point=4096, num_votes=3, test_area=5, visual=False)
The number of test data is: 68
---- EVALUATION WHOLE SCENE----
Inference [1/68] Area_5_office_41 ...
100%|██████████████████████████| 3/3 [02:47<00:00, 55.71s/it]
[7.25445875e-01 3.07780188e-01 4.15225488e-03 0.00000000e+00
 0.00000000e+00 3.10150609e-04 0.00000000e+00 6.61627936e-02
 0.00000000e+00 0.00000000e+00 2.81635576e-01 0.00000000e+00
 0.00000000e+00]
Mean IoU of Area_5_office_41: 0.1260
----------------------------
Inference [2/68] Area_5_hallway_15 ...
100%|██████████████████████████| 3/3 [02:37<00:00, 52.63s/it]
[0.64243998 0.54366874 0.00370053 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.00080778]
Mean IoU of Area_5_hallway_15: 0.1701
----------------------------

Mean IoU of Area_5_office_41: 0.1260
Mean IoU of Area_5_hallway_15: 0.1701
miou仅仅为0.1260、0.1701
想了很久也想不出来，能帮忙分析一下吗？谢谢！！！

**Comment by yanx27** [comment] 2021-06-25 05:16
Hi @yezi1996 , did you solve it? I'm not sure that whether the problem is caused by [pull request #113](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/pull/113) and I'm currently very busy without time to check it. Now, I reverse the version of codes to the version before the pull. You can try again.

**Comment by yanx27** [comment] 2021-06-29 15:26
@yezi1996 Hi, did you solve this problem, it's time to close this issue, if you have any problem, you can open this again.

**Closed by yanx27** 2021-06-29 15:26 UTC
